### ISSUE TITLE
NAT Traversal

### ISSUE THREAD

**Issue by RichRenwick** [genieacs/genieacs#124]
Hi, the only thing I can see mention XMPP or STUN is from 2014 when GenieACS did not support either.  Is this still the case and if so, are there any plans to support devices that are NAT'ed?

Thanks,
      Rich

**Comment by zaidka** [comment]
It's still not supported. I don't imagine it's incredibly difficult to implement, it's just never been a priority given the other features being worked on. It's also not in the road map at this time, sorry! Patches are welcome though.

**Comment by RichRenwick** [comment]
Ok thanks.

**Comment by spencerlambert** [comment]
@RichRenwick STUN is now supported in version 1.1.  I've got it working in my installation.  If you need help, I'd be happy to assist.

**Comment by kennsche** [comment]
I have a working setup of GenieACS with TR69 enabled devices to which I can successfully issue GET and SET parameters. I am now investigating how to have this done via NAT. I was thinking something on the line of port-forwarding through the NAT but through tests I discovered that this may not be possible.

ACS server is listening on port 8667 on its own public IP. The CPE is behind NAT with another public IP address but has private IP 192.168.0.3. The CPE is connecting to the ACS on the same port (8667). The ACS does receive the initial connection of the CPE together with some details about it. So far so good.

On event that I want to have the ACS send get/set parameters to the CPE (behind NAT), GenieACS would have stored the private IP of the CPE (192.168.0.3) not the public IP (therefore port-forwarding doesn't seem possible)

I am now investigating how to do this via STUN or XMPP. **@spencerlambert** Would you have some initial pointers where to start configuring it in relation to GenieACS please?

**Comment by spencerlambert** [comment]
@kennsche by default STUN support is off.  It requires two things: 

1.  A STUN server running on the same server Genie is running.  The STUN server needs to also allow other applications to bind to the STUN port.  I use this STUN server, [STUNTMAN](https://github.com/jselbie/stunserver).  Use the `--reuseaddr` option when running the STUN server.

2. In your Genie `config.json` file, add the following option: `"UDP_CONNECTION_REQUEST_PORT" : 3478`

**Comment by RichRenwick** [comment]
@spencerlambert Sorry for not seeing your updates from last year.  For some reason I wasn't getting email notifications.  I have moved on in terms of projects now and we ended up using a different ACS solution back on the old project.
Thanks though :)
