### ISSUE TITLE
The 1st appearance of the device

### ISSUE THREAD

**Issue by Kniz1981** [genieacs/genieacs#279]
When the device first appears in ACS, it is necessary to update all the parameters since initially they are not visible. How to do this when the device first appears updating all parameters?

**Comment by zaidka** [comment]
This has been discussed previously in the mailing list. Feel free to post there if you can't find the info you're looking for.

**Comment by redasabry** [comment]
fter greeting
I have been wanting to block several router with each other and after testing systems, a lot described to your system and I am currently working on the system on Ubuntu Server 14.4, but I have several consequences
It does not invoke the ip assigned to it on the system
I tried to search all roads for the best ways but there is no solution
But if I found you I wanted you to help me

**Comment by akcoder** [comment]
Please take your questions to the mailing list. GitHub is for defect
tracking.
