### ISSUE TITLE
(HTTP) connection request fail

### ISSUE THREAD

**Issue by zavarat** [genieacs/genieacs#280]
Now, I'm testing with blow CPE. 
https://github.com/Orange-OpenSource/tr069agent

Boot sequence performed normally. (CPE is registed in ACS)
But when I try "GetParameterValue", I got error result. 

I think, the "ConnectionRequest" is not performed normally.
please check blow.

(1) Send HTTP GET Message from ACS to CPE : OK
(2) Responce HTTP 401 Message from CPE to ACS : NOK
* GenieACS is not processing this message.
* I insert the some log in api-functions.js (api-functions.js)

```
return request = http.get(options, function(res) {

  }).on('error', function(err) {
	tracer.log('err='+err); // 

    request.abort();
    return callback(statusToError(0));
  })
```

* error log is blow.

`err=Error: socket hang up`

* Now I testing using VM in same network. So, I think network delay is not reason.

* this is tcpdump file in ACS, please find #816, #818 message
https://drive.google.com/file/d/1pJO32omUsLltK-lZr2Gnv8f731Jy6X8o/view?usp=sharing

**Comment by zaidka** [comment]
The response from the client looks to be invalid according to the HTTP spec. Headers must end with 0x0d followed by 0x0a (i.e. CRLF) and the last header must end with an additional CRLF sequence.

**Comment by zavarat** [comment]
I'm inserted additional CRLF sequence in CPE's 401 message.
Then I re-try "GetParameterValue", got the following results.

1. still found the fail message - **Device is offline** - in GUI. 
2. still found the error log - **Error: socket hang up** - that I mentioned before.
3. **When I investigate the tcpdump and debug file, every message is fine.**
- ConnectionRequest and GetParameterValue 
 
* I insert the some log in api-functions.js (api-functions.coffee)

```
  statusToError = function(statusCode) {
	tracer.log('statusCode='+statusCode); // "statusCode" is "0" 

    switch (statusCode) {
      case 200:
      case 204:
        return null;
      case 401:
        return new Error('Incorrect connection request credentials');
      case 0:
        return new Error('Device is offline');  // found this message in GUI 
      default:
        return new Error("Unexpected response code from device: " + statusCode);
    }
  };
```

```
return request = http.get(options, function(res) {

  }).on('error', function(err) {
	tracer.log('err='+err); // error message is  "Error: socket hang up"

    request.abort();
    return callback(statusToError(0));
  })
```

```
connectionRequest = function(deviceId, callback) {
...
    conReq = function() {
	  tracer.log(''); //
...
      return httpConReq(connectionRequestUrl, username, password, CONNECTION_REQUEST_TIMEOUT, function(err) {
		tracer.log(''); // print this line 

        if (udpSent) {
          return callback();
        }
		tracer.log('return cb'); // print this line 
        return callback(err);
      });
    };
...
}
```

* genieacs log
```
2018-01-08T15:32:46+0900 <log> auth.js:48 (Object.exports.digest)
2018-01-08T15:32:46+0900 <log> api-functions.js:188 (ClientRequest.<anonymous>)
2018-01-08T15:32:46+0900 <log> api-functions.js:183 (ClientRequest.<anonymous>) err=Error: socket hang up
2018-01-08T15:32:46+0900 <log> api-functions.js:119 (statusToError) statusCode=0
2018-01-08T15:32:46+0900 <log> api-functions.js:272 ()
2018-01-08T15:32:46+0900 <log> api-functions.js:278 () return cb
```

* this is tcpdump file in CPE, please find #63~#108 message
https://drive.google.com/file/d/1t8IS5S1fjhruuJfiSKq9PfHAP5A19y2i/view?usp=sharing
(Now I'm using nginx web server for HTTP authentification)

* this is debug file in ACS, please find line #3339
https://drive.google.com/file/d/115S_tZGt_-Ub956vXK1Jr-RzpWhScUu_/view?usp=sharing

**Comment by zaidka** [comment]
Still doesn't look like it's valid HTTP. Sorry can't offer more help as it's clearly a client issue. I suggest raising this to the developers of the client.
