### ISSUE TITLE
multi instances of geniacs 

### ISSUE THREAD

**Issue by Anisel** [genieacs/genieacs#282]
Hi,
I wonder if genieacs supports multi instances.
the purpose of this feature is to have multi user and each user can show and manage only his own devices.
is this feature can be supported ?

**Comment by DrumSergio** [comment]
Hi Anisel,

I was in need of a similar config some time ago, and I realized that it would need to make deep changes to the code.
The solution I found was to launch different instances of GenieACS on the same machine, using different ports for every service, of course.
The key here is to launch every instance with a different config file. So you would call, for example, the binary genieacs-cwmp with an argument --config (I don't have it at hand, I think it is --config, but you can search it better on the mailing list) adding the location of the config file. You can find an example of a config file in the wiki here: https://github.com/genieacs/genieacs/wiki/GenieACS-General-Config

Hope it helps.

**Comment by Anisel** [comment]
thanks a lot Sergio,
this could help but it remains the second part which is the genieacs-gui.
is this idea is can be applied on the genieacs GUI ?

**Comment by DrumSergio** [comment]
Of course. You launch another rails app in another directory and in another port. Besides that, you have to adjust the port for the genieacs-nbi service to communicate. The default is at 7557, so you simply change it to the value of the new instance. I think I changed the port on this file: https://github.com/genieacs/genieacs-gui/blob/master/config/environments/development.rb

**Comment by Anisel** [comment]
many tanks sergio
