### ISSUE TITLE
How to add custom RPC function to ACS

### ISSUE THREAD

**Issue by don11995** [genieacs/genieacs#284]
Hello! I'm trying to implement base TR-069 under Android and I managed to support several necessary commands on the device (Reboot and Download). 

I need to realize three simple functions:
1. Reboot
2. Download firmware or file
3. Get device logs 

The first two functions I already realized and now I need to add a new command to the server (genieacs) to get logs from the device.
For example, I get over http:
```
<soap:Body>
<cwmp:GetDeviceLogs/>
</soap:Body>
```
and then download the logs to the server.

Can I somehow realize it? Unfortunately, I do not really understand javascript and ruby, is there is any possibility to add some kind of a config file so that this button (get logs) appeared on the server?

Sorry for the trouble and I will be very grateful for any help, thanks in advance.

Also interesting:
When I receive Download request I'm starting downloading the file and after it downloaded and checked, I'm initing session with "TRANSFER COMPLETE" event with actual TransferComplete RPC, StartTime and CompleteTime, but these parameters do not updating in Download section corresponding fields on the server. Filelds StartTime and CompleteTime for Download always with unknown time on the server. Am I doing something wrong?

**Comment by akcoder** [comment]
Please take this to the mailing list. Github is for defect tracking, not
support requests.
