### ISSUE TITLE
auth device to service acs 7547

### ISSUE THREAD

**Issue by nick9015** [genieacs/genieacs#289]
Hi, I can put password to the ACS service so that not all devices can connect to my server, I can not find where to configure this. On my modem, I charge any username and password, and I can see the information. Thank you

![image](https://user-images.githubusercontent.com/6010847/36390179-d873d2f2-1580-11e8-85d1-15ba80c1199f.png)

**Comment by zaidka** [comment]
GenieACS doesn't implement device authentication. You'll need to put it behind a proxy server which takes care of authentication.
