### ISSUE TITLE
GenieACS creates object with wrong name

### ISSUE THREAD

**Issue by okraits** [genieacs/genieacs#294]
I want to add an interface to a device. Therefor I defined the following object:

    {
        "_id" : "network-Leitstelle",
        "_keys" : [ 
            "General.LogicalName"
        ],
        "General" : {
            "LogicalName" : "Leitstelle",
            "OperatingPhysicalInterfaceName" : "tun1",
            "OperatingProtocol" : "none"
        }
    }

I want to add the object with a preset:

    {
        "_id" : "VR2-105196",
        "channel" : "",
        "weight" : 1,
        "precondition" : "{\"InternetGatewayDevice.DeviceInfo.SerialNumber\":\"VR2-105196\"}",
        "configurations" : [ 
            {
                "type" : "add_object",
                "name" : "InternetGatewayDevice.X_TDT-DE_Interface",
                "object" : "network-Leitstelle"
            }, 
            {
                "type" : "add_tag",
                "tag" : "configured"
            }
        ],
        "schedule" : "",
        "events" : {}
    }

The object (interface) is added first and then renamed. The issue appears when renaming the object.
The object (interface) is renamed to 'undefined', not to 'Leitstelle'.

This used to work with GenieACS v1.0 at least.

**Comment by akcoder** [comment]
Oliver, configuring devices using presets and objects is no longer the
preferred method. Provision scripts are the new (and *much* better) way to
create object instances, manage config, etc.

-dan

On Thu, Apr 12, 2018 at 10:21 PM, Oliver Kraitschy <notifications@github.com

**Comment by okraits** [comment]
I know but I don't want to refactor working customer setups without a real need.

And existing functionality should continue to work and not break, IMO.

**Comment by okraits** [comment]
@zaidka Thank you for the quick fix!

**Comment by zaidka** [comment]
You're welcome. Thanks for the detailed bug report.
