### ISSUE TITLE
Can you create a task for multiple CPEs without specifying the device?

### ISSUE THREAD

**Issue by terolando** [genieacs/genieacs#295]
Can you create a task for multiple CPEs without specifying the device?

I would like to know if I have to do this command for example to play an update file for several CPEs at the same time?

curl -i http: // localhost: 7557 / devices / "do not specify a device" / tasks? conection_request -X POST --data '{"name": "download", "file": "5ad5c01135abc7f14e363306", "filename" : "atyaliza-stx_lite5.xml"} '

Or if at least you have in a Preset, after the condition I can create a task of playing this file to everyone who is in the condition.

Because updating one device at a time is the only thing that is not right.

**Comment by akcoder** [comment]
Please take this to the mailing list and close this ticket and the one you
opened for the GUI. GitHub is for defect tracking, not configuration
questions.

-dan
