### ISSUE TITLE
Upload configuration file from CPE

### ISSUE THREAD

**Issue by maxpushpashev** [genieacs/genieacs#296]
How to upload a configuration file from the CPE using GenieACS it is possible?
I interested paragraph "A.4.1.5 Upload" page 110 of this:
https://www.broadband-forum.org/technical/download/TR-069_Amendment-5.pdf
I have need backup config file for all my device.

**Comment by akcoder** [comment]
GitHub is for defect tracking, not configuration issues. Please close this
ticket and take it to the mailing list.

-dan
