### ISSUE TITLE
Ping/tracert from CPE to internet via ACS

### ISSUE THREAD

**Issue by LeVanVuong93** [genieacs/genieacs#315]
Hi everybody,

I was setup GenieaACS successfully. Currently, i'm research to how to CPE ping / tracert to a public IP address and return result on ACS.
Who built this feature, can you tell me how to do it?
Many thanks!

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please close this
issue and take your question to the mailing list.

**Comment by LeVanVuong93** [comment]
Hi akcoder,
I'm so sorry, Could you point me to the mailing list ? Pls.
