### ISSUE TITLE
How to stop spliting of parameter UI

### ISSUE THREAD

**Issue by mushir3589** [genieacs/genieacs#323]
Hi All

For suppose my parameter that comes from a client is Device.LANDevice.1.LANHostConfigManagement.IPInterfaceNumberOfEntries

but in UI it splits and shows as below 
1.Device.LANDevice
2.Device.LANDevice.1
3.Device.LANDevice.1.LANHostConfigManagement
4.Device.LANDevice.1.LANHostConfigManagement.IPInterfaceNumberOfEntries
I don't want this I want just show not split parameter Device.LANDevice.1.LANHostConfigManagement.IPInterfaceNumberOfEntries

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please close this ticket and take your question to the mailing list. 

-dan
