### ISSUE TITLE
API for GetParameterNames (refreshObject) with NextLevel specified.

### ISSUE THREAD

**Issue by tilin63** [genieacs/genieacs#331]
I used refreshObject API intending to obtain ParameterName information.  However, the NextLevel is always set to 1.  Is there any chance that I can set the NextLevel to 0?

Also, the CPE that connects to the GenieACS I setup does not take empty string for GetParameterNames (I know, it's against the CWMP standard).  However, if I wish to create another Preset with GetParameterNames and NextLevel = 0, is there anyway to do this?

Thanks.

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please close this
issue and take your request to the mailing list.

**Comment by tilin63** [comment]
My fault.  Sorry about that.
