### ISSUE TITLE
issues about multi-instance handling 

### ISSUE THREAD

**Issue by zavarat** [genieacs/genieacs#334]
Hi.

I'm facing a problem when trying to "refresh" (getParameterValues) on parameters that contain varying multi-instances.

Initially, I connected a CPE containing 10 instances to the server, and tried to refresh the top node (Device.) And It's performed normally. (please see log1, and find parameters "Device.X_MINOLAB_PkgMgr.Application")

Next, I attempted to "refresh" the CPE by reducing it to 5 instances. At this time, 1 to 5, 6, 10 instances remain in the GUI. When I view the dump log, ACS sends additional unusual requests to the CPE. (please see log2)

ps. The ACS under test is the latest version from the master branch.

**Comment by zaidka** [comment]
Hmm looks like it's failing to remove previous instances that no longer exist. Will look into it. Did you test against v1.1.3?

**Comment by zaidka** [comment]
I couldn't reproduce the issue. Would be great if you can provide steps to reproduce using the simulator.

**Comment by zavarat** [comment]
Thank you for your reply.

I tried the above test with the ACS v1.1.3. On the Web GUI, I have found that instance is decreasing normally. 
But, it seems to be performing GPN and GPV several times. I wonder if this works normally (or intended).
(please see dump (V113_01_ins_10.txt, V113_02_ins_05.txt)

I did the test again on the v1.2.0 (master branch) updated today. Instances on the GUI did not decrease. The log is also attached.

Sorry, I tried to reproduce the problem using easycwmp, but it did not work out. 
Please let me know if there is anything that can help you with the problem.

[V113_01_ins_10.txt](https://github.com/genieacs/genieacs/files/2786375/V113_01_ins_10.txt)
[V113_02_ins_05.txt](https://github.com/genieacs/genieacs/files/2786376/V113_02_ins_05.txt)

[V120_01_ins_10.txt](https://github.com/genieacs/genieacs/files/2786377/V120_01_ins_10.txt)
[V120_02_ins_05.txt](https://github.com/genieacs/genieacs/files/2786378/V120_02_ins_05.txt)

**Comment by zaidka** [comment]
Something's not right about the flow of requests. Can you confirm that you have no modifications in lib/session.js? Otherwise the device object in the database might be corrupted. See if you can reproduce the problem after you delete the device.

**Comment by zavarat** [comment]
Hi.

Currently, there is no change in the base source at all. And I attached some log. 
please find it.  The test procedure is as follows.

1. CPE Boot (after remove device info. in DB)
2. getParameterValues (instance count 10)
3. CPE Boot (after reduce instance count 5)
4. getParameterValues (instance count 5)

[cpe_dump.txt](https://github.com/genieacs/genieacs/files/2802803/cpe_dump.txt)
[asc_log.txt](https://github.com/genieacs/genieacs/files/2802804/asc_log.txt)

**Comment by zaidka** [comment]
I finally managed to reproduce the problem. It only shows up when the device doesn't maintain a single TCP connection throughout the session which seems to be the case for your particular device. Restoring session data from cache is broken. Will fix soon. Thanks for all the info.
