### ISSUE TITLE
Disabling logs

### ISSUE THREAD

**Issue by gittela** [genieacs/genieacs#337]
We're having some trouble with excessive logging from Genieacs, it doesn't seem to adhere to the "LOG_INFORMS" : false setting in config.json. Are there any other settings we can fiddle with? Note that we do not get debug, this is just a _lot_ of [INFO] messages, as in a couple of hundred megabytes pr day. We are running a bit of testing on this installation and we where hoping to disable some of the logging without routing it to dev/null.

**Comment by gittela** [comment]
As a side note, if we don't specify a log file it goes straight to syslog (messages)

**Comment by zaidka** [comment]
The option LOG_INFORM was for the old v1.0 log format and has no effect in v1.1 and there's no way to reduce the amount of logs.

It's recommended to have the access logs go to a file rather than than journald or syslog. And setup logrotate to make sure you don't run out of space.

**Comment by gittela** [comment]
Ok, thanks. That explains why it didn't work, at least

:-)
../~howard
