### ISSUE TITLE
Task queued but not processed from API but not from UI

### ISSUE THREAD

**Issue by ppkamp** [genieacs/genieacs#343]
Hello,

I'm trying to call refreshObject from API with the option connection_request, but I always get a 202 response (Task queued but not processed). On the other hand, if I push the refresh button in GenieACS-GUI the task is processed inmediately.  (The same happens with the setParameterValues API call)

Both API calls are fired from a different server, not from localhost. I tried also using a greater timeout parameter (50000) with the same result.

What could be the problem?

Thank you in advance.

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please close this
issue and use the support forum <https://forum.genieacs.com/>.

**Comment by ppkamp** [comment]
Ok, I'm going to close it, but for me is a defect that the API behaviour is different than GUI's. I don't know if it is a bug or a misconfiguration.
