### ISSUE TITLE
401 auth problem

### ISSUE THREAD

**Issue by zzzacbbt** [genieacs/genieacs#344]
When I use the genieacs server, I found a problem, like this
[401.zip](https://github.com/genieacs/genieacs/files/3245544/401.zip)
IN CPE , config as follow
![image](https://user-images.githubusercontent.com/38638768/58770980-77c5cc00-85e4-11e9-9b1e-923059642f31.png)
when I use this config in CPE as follow,it is normal.
![image](https://user-images.githubusercontent.com/38638768/58771032-a9d72e00-85e4-11e9-8b43-383dec197fed.png)
Have some idea to solve it ?

**Comment by zzzacbbt** [comment]
![image](https://user-images.githubusercontent.com/38638768/58771970-8c589300-85e9-11e9-8102-278e323eff62.png)
From the packet, Content length =0 ,I think this is reason,but I don't know how to solve it.

**Comment by zzzacbbt** [comment]
@zaidka

**Comment by zzzacbbt** [comment]
InternetGatewayDevice.ManagementServer.ConnectionRequestUsername InternetGatewayDevice.ManagementServer.ConnectionRequestPassword
![image](https://user-images.githubusercontent.com/38638768/58774359-a0a18d80-85f3-11e9-9100-4506d92da5ec.png)
I FOUND ConnectionRequestUsername  and Password no found

**Comment by zaidka** [comment]
This issue tracker is for reporting bugs. For support requests, use the forum. Make sure to describe your issue clearly and allow time for someone kind enough to offer help.
