### ISSUE TITLE
Mikrotik Authentication

### ISSUE THREAD

**Issue by youssefbj** [genieacs/genieacs#346]
Hi everyone,

Last week i was able to install genieacs successfully . after that i have installed Mikrotik RouterOS for test.
I have to change the config file "/genieacs/config/auth-sample.js" to establish connection.
I tried to connect Mikrotik to genieacs , and the connection has established successfully.
After that i installed FreeRadius . My problem is , is it any solution to integrate Freeradius with genieacs and set the authentication via freeradius instead of genieacs ??.
what i mean is :

                            Authentication                            
Mikrotik Router ------------------->> FreeRadius ------------------->>> genieacs .

can you help me please ?Thanks.

**Comment by akcoder** [comment]
GitHub is for defect tracking, not support requests. Please close this issue and create an entry on the forum. 

-dan

**Comment by youssefbj** [comment]
Hi akcoder , 
Thank you for the help . i will close this issue.
