### ISSUE TITLE
GUI-Crash when jumping to a sorted List

### ISSUE THREAD

**Issue by HerrMaxwell** [genieacs/genieacs#348]
Kinda new here... hope i get everything right...

Right now i have GenieACS running with 307 devices. I use the standard of 10 entries per site. So i have 31 pages . After using the sort function with any header (e.g. software version, MAC, IP...) and jumping directly to page 16 or higher rails crashes:

EOFError in DevicesController#index
end of file reached
Rails.root: /usr/share/genieacs-gui
Application Trace | Framework Trace | Full Trace
Request
Parameters:
{"page"=>"30", "query"=>"{}", "sort"=>"InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID"}

Tested it with different settings. Jumped to different sites, used the arrow, used different headers.

System runs Debian 9.8 and GenieACS 1.1.3

Couldnt reproduce it on an older version of GenieACS . Instead of a crash i see only empty pages. 
Not sure about the right vocabulary, but could it be some kind of pointer problem?

Best regards,
Max

**Comment by miami1983** [comment]
i have same issue and still unable to debug or fix it

**Comment by miami1983** [comment]
also we have to extend the page with 100 raw or other functionality

**Comment by zaidka** [comment]
This belongs in genieacs-gui repo. Please submit there. Also please make sure to include any relevant logs from genieacs-gui and genieacs-nbi.
