### ISSUE TITLE
 Failed to enable unit: Unit file genieacs-cwmp.service does not exist.

### ISSUE THREAD

**Issue by pchechani** [genieacs/genieacs#353]
https://github.com/genieacs/genieacs/blob/master/docs/installation-guide.rst 

following the above installation guide i see i can not start the service. Is there bug there or documentation needed more info there.

I was trying to create service via systemctl edit --force genieacs-cwmp

**Comment by pchechani** [comment]
I am using ubuntu-desktop 18.04.2

**Comment by zaidka** [comment]
The installation guide is complete and has been tested. Looking at the error message it sounds like you may exited the editor without saving. Please double check.

**Comment by pchechani** [comment]
I have tried the installation guide on ubuntu server edition and it is working.
Wondering if we have SSL/TLS setup guide. currently it shows as TODO under HTTPS section @https://docs.genieacs.com/en/latest/https.html

**Comment by pchechani** [comment]
closing the issue as it is not real issue.
