### ISSUE TITLE
Notify other service of CPE events

### ISSUE THREAD

**Issue by akcoder** [genieacs/genieacs#46]
I needed a way to notify my subscriber management software of events that happen on a CPE. This is addressed in pull request #45. I tried to create this as generic as possible, and you can change which events you want to be notified for by adding/removing the event names in the config variable NOTIFICATION_TYPES. Event names are comma delimited. Example: "1 BOOT,2 PERIODIC...9 REQUEST DOWNLOAD,M Reboot"

**Comment by jlaffaye** [comment]
I'm also interested by this feature.
When the customer does a factory reset, I have to (re)setup the VoIP configuration.
For security reasons, I want to regenerate the SIP password so I need to be notified to do that and create the task in genieacs.

**Comment by akcoder** [comment]
Checkout my branch and configure it.

**Comment by DrumSergio** [comment]
Now implemented in v1.1. Close Issue?

**Comment by sof1105** [comment]
Not yet implemented ??
when will this be available

**Comment by akcoder** [comment]
This will never be available :). My code was a stop-gap measure until
GenieACS v1.1 was released. GenieACS v1.1 supports provision and extension
scripts. Between the two, you can do everything this patch could do, and a
lot more.
